TrajectoryPlannerROS:
  acc_lim_x: 2.5
  acc_lim_theta:  3.2

  max_vel_x: 0.25
  min_vel_x: -0.1

  max_vel_theta: 0.4
  min_vel_theta: -0.4
  min_in_place_vel_theta: 0.2

  holonomic_robot: false
  escape_vel: -0.1

  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.15
  latch_xy_goal_tolerance: false

  # forward simulation parameters
  sim_time: 2.0

  # path cost function weights
  path_distance_bias: 1.0
  goal_distance_bias: 0.2
  occdist_scale: 0.01
  
  heading_scoring: false
  prune_plan: true
  meter_scoring: true
  dwa: false
  