TrajectoryPlannerROS:
  acc_lim_x: 2.5
  acc_lim_theta:  3.2

  max_vel_x: 0.25
  min_vel_x: -0.1

  max_vel_theta: 0.5
  min_vel_theta: -0.5
  min_in_place_vel_theta: 0.2

  holonomic_robot: false
  escape_vel: -0.1

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.4
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 1.0
  # sim_granularity: 0.02
  # angular_sim_granularity: 0.02
  # vx_samples: 6
  # vtheta_samples: 20
  # controller_frequency: 20.0

  pdist_scale: 4
  gdist_scale: 0.5
  # occdist_scale: 0.01
  # heading_lookahead: 0.325
  heading_scoring: false
  # dwa: false
  # publish_cost_grid_pc: true
  